- name: variables to print
  hosts: web
  vars: 
    COURSE: Devops with AWS
    DURATION: 120 HRS
    TRAINER: Sivakumar reddy
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: I am learing {{COURSE}}, DURATION is {{DURATION}}, TRAINER is {{TRAINER}}
      


