- name: varaibales from the inventory
  hosts: web
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: I am learning {{COURSE}}, DURATION is {{DURATION}}, TRAINER is {{TRAINER}}
      
