- name: check a number is less than a 10 or not
  hosts: local
  connection: local
  vars_prompt:
  - name: my_number
    prompt: please enter the number
    private: false
  tasks: 
  - name: print this if less than 10
    ansible.builtin.debug:
      msg: Given number is {{ my_number}}, is less than 10
    when: my_number | int < 10

  - name: print this if greater than or equal to 10
    ansible.builtin.debug:
      msg: Given number is {{my_number}}, greater than or equal to 10
    when: my_number | int >= 10
    
